name: hvdc_user
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.2+3

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.0
  dots_indicator: ^3.0.0
  get: ^4.6.6
  font_awesome_flutter: ^10.7.0
  hexcolor: ^3.0.1
  table_calendar: ^3.1.0
  google_sign_in: ^6.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  wordpress_client: ^8.4.1
  flutter_svg: any
  lottie: ^2.7.0
  badges: ^3.1.2
  tiny_alert: ^1.1.1
  fluttertoast: ^8.2.5
  carousel_slider: ^4.2.1
  image_picker_ios: ^0.8.9+1
  image_picker: ^1.0.8
  dio: ^5.4.3+1
  flutter_widget_from_html: ^0.14.11
  flutter_faq: ^1.0.1+1
  url_strategy: ^0.2.0
  dropdown_search: ^5.0.6
  overlay_search: ^0.2.8
  path_provider: ^2.1.3
  file_saver: 0.2.10
  permission_handler: ^11.0.1
  shimmer: ^3.0.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/onboarding/
    - assets/app_icons/
    - assets/web_banner/
    - assets/animation/
    - assets/

  